version: "3.8"

services:
  # ----------------- MySQL -----------------
  db:
    image: mysql:8.0
    container_name: pos-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: limit500?        # 開発用
      MYSQL_DATABASE: pos_app_db
    ports:
      - "3307:3306"                        # ホスト→コンテナ
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # ----------------- FastAPI -----------------
  backend:
    build:
      context: ./backend                   # backend/Dockerfile
    container_name: pos-backend
    restart: unless-stopped
    env_file:
      - .env                               # DB_USER 等をここに書く
    depends_on:
      - db
    ports:
      - "8000:8000"                        # ホスト→コンテナ (API)

  # ----------------- Next.js -----------------
  frontend:
    build:
      context: ./frontend                  # frontend/Dockerfile
    container_name: pos-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=https://pos-backend.ashystone-fb341e56.japaneast.azurecontainerapps.io   # ← フロント→バックエンド
    ports:
      - "3000:3000"                        # ホスト→コンテナ (Web)

volumes:
  mysql_data:
