# docker-compose.azure.yml - Azure Production Simulation
version: "3.8"

services:
  # ----------------- FastAPI Backend -----------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.production
    container_name: pos-backend-azure
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    environment:
      ENV_FILE: .env.production
      ENV: production
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ----------------- Next.js Frontend -----------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.production
    container_name: pos-frontend-azure
    restart: unless-stopped
    env_file:
      - ./frontend/.env.production
    environment:
      ENV_FILE: .env.production
      NODE_ENV: production
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: pos-azure-network