# .github/workflows/deploy.yml
name: deploy-to-aca

on:
  workflow_run:
    workflows: ["build-and-push"]   # ← ci.yml の name と一致
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # (1) Azure にログイン
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # (2) CLI で Container Apps を作成／更新
      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          # azcliversion: 2.55.0
          inlineScript: |
            set -eox pipefail

            RG="pos-mvp-rg"
            ENV="pos-mvp-env"
            REGISTRY="${{ secrets.ACR_LOGIN_SERVER }}"
            USER="${{ secrets.ACR_USERNAME }}"
            PASS="${{ secrets.ACR_PASSWORD }}"
            TAG="${{ github.event.workflow_run.head_sha }}"

            # ---------- backend ----------
            if az containerapp show -g $RG -n pos-backend &>/dev/null; then
              az containerapp update \
                -g $RG -n pos-backend \
                --image $REGISTRY/pos-backend:$TAG
            else
              az containerapp create \
                -g $RG -n pos-backend --environment $ENV \
                --image $REGISTRY/pos-backend:$TAG \
                --target-port 8000 --ingress external \
                --env-vars DB_USER=root DB_PASSWORD='limit500?' DB_HOST=pos-db DB_PORT=3306 DB_NAME=pos_app_db

              az containerapp registry set \
                -g $RG -n pos-backend \
                --server $REG \
                --username "${{ secrets.ACR_USERNAME }}" \
                --password "${{ secrets.ACR_PASSWORD }}"
            fi

            # ---------- frontend ----------
            if az containerapp show -g $RG -n pos-frontend &>/dev/null; then
              az containerapp update \
                -g $RG -n pos-frontend \
                --image $REGISTRY/pos-frontend:$TAG
            else
              az containerapp create \
                -g $RG -n pos-frontend --environment $ENV \
                --image $REGISTRY/pos-frontend:$TAG \
                --target-port 3000 --ingress external \
                --env-vars NEXT_PUBLIC_API_URL=https://pos-backend.internal.ashystone-fb341e56.japaneast.azurecontainerapps.io

              az containerapp registry set \
                -g $RG -n pos-frontend \
                --server $REG \
                --username "${{ secrets.ACR_USERNAME }}" \
                --password "${{ secrets.ACR_PASSWORD }}"
            fi

            # deploy.yml の inlineScript 末尾に追記
            # ---------- database ----------
            if az containerapp show -g $RG -n pos-db &>/dev/null; then
              echo "pos-db already exists"
            else
              az containerapp create \
                -g $RG -n pos-db --environment $ENV \
                --image mysql:8.0 \
                --target-port 3306 --ingress internal \
                --cpu 1 --memory 2Gi \
                --env-vars MYSQL_ROOT_PASSWORD='limit500?' \
                           MYSQL_DATABASE=pos_app_db \
                --min-replicas 1
            fi

